const Phones = [
  {
    id: 1,
    name: "iPhone 11",
    price: 49990,
    company: "Apple",
    category: "flagship",
  },
  {
    id: 2,
    name: "Note 8 Pro",
    price: 13990,
    company: "Xiaomi",
    category: "budget",
  },
  {
    id: 3,
    name: "Galaxy S10",
    price: 59990,
    company: "Samsung",
    category: "flagship",
  },
  {
    id: 4,
    name: "Galaxy A51",
    price: 16990,
    company: "Samsung",
    category: "budget",
  },
  {
    id: 5,
    name: "Pixel 4",
    price: 49990,
    company: "Google",
    category: "flagship",
  },
  {
    id: 6,
    name: "Nord CE",
    price: 22990,
    company: "OnePlus",
    category: "mid-range",
  },
  {
    id: 7,
    name: "Mi 11 Lite",
    price: 21990,
    company: "Xiaomi",
    category: "mid-range",
  },
  {
    id: 8,
    name: "iPhone 12",
    price: 79990,
    company: "Apple",
    category: "flagship",
  },
  {
    id: 9,
    name: "Galaxy S21",
    price: 69990,
    company: "Samsung",
    category: "flagship",
  },
  {
    id: 10,
    name: "Pixel 5",
    price: 59990,
    company: "Google",
    category: "flagship",
  },
  {
    id: 11,
    name: "Mi 11 Ultra",
    price: 69990,
    company: "Xiaomi",
    category: "flagship",
  },
  {
    id: 12,
    name: "iPhone 12 Pro",
    price: 99990,
    company: "Apple",
    category: "flagship",
  },
  {
    id: 13,
    name: "Galaxy S21 Ultra",
    price: 99990,
    company: "Samsung",
    category: "flagship",
  },
  {
    id: 14,
    name: "Pixel 4a",
    price: 31990,
    company: "Google",
    category: "mid-range",
  },
  {
    id: 15,
    name: "iPhone SE",
    price: 39990,
    company: "Apple",
    category: "flagship",
  },
  {
    id: 16,
    name: "Galaxy A72",
    price: 34990,
    company: "Samsung",
    category: "mid-range",
  },
  {
    id: 17,
    name: "Pixel 4a 5G",
    price: 45990,
    company: "Google",
    category: "flagsip",
  },
  {
    id: 18,
    name: "iPhone 12 mini",
    price: 69990,
    company: "Apple",
    category: "flagship",
  },
  {
    id: 19,
    name: "Galaxy A52",
    price: 24990,
    company: "Samsung",
    category: "mid-range",
  },
  {
    id: 20,
    name: "Narzo 10",
    price: 11990,
    company: "Realme",
    category: "budget",
  },
];

export default Phones;
